=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioSEIS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:complexType name="tipoInventario">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:choice>
                <xsd:element name="lapiz" type="atributosLapiz"/>
                <xsd:element name="cuaderno" type="atributosCuaderno"/>
                <xsd:element name="boligrafo" type="atributosBoligrafo"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="atributosLapiz">
        <xsd:sequence>
            <xsd:element name="dureza" minOccurs="0" maxOccurs="1" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="atributosCuaderno">
        <xsd:sequence>
            <xsd:element name="numHojas" minOccurs="1" maxOccurs="1" type="xsd:int"/>
            <xsd:element name="estilo" minOccurs="1" maxOccurs="1" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="atributosBoligrafo">
        <xsd:sequence>
            <xsd:element name="precio" minOccurs="1" maxOccurs="1" type="xsd:float"/>
            <xsd:element name="color" minOccurs="0" maxOccurs="1" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="inventario" type="tipoInventario"/>

</xsd:schema>

=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioSEIS.xml
<?xml version="1.0" encoding="UTF-8" ?>
<inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="ejercicioSEIS.xsd">
    <boligrafo>
        <precio>1.3</precio>
        <color>Verde</color>
    </boligrafo>
    <cuaderno>
        <numHojas>150</numHojas>
        <estilo>Cuadriculado</estilo>
    </cuaderno>

    <lapiz>
        <dureza>Mucha</dureza>
    </lapiz>

    <boligrafo>
        <precio>2</precio>
    </boligrafo>
    <lapiz>

    </lapiz>

    <cuaderno>
        <numHojas>300</numHojas>
        <estilo></estilo>
    </cuaderno>

</inventario>
