=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioTRESb.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!--Un raton o un teclado o un monitor-->

    <xsd:element name="productos">
        <xsd:complexType>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element name="raton" type="xsd:string"/>
                <xsd:element name="teclado" type="xsd:string"/>
                <xsd:element name="monitor" type="xsd:string"/>
            </xsd:choice>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="atributos">
        <xsd:sequence>
            <xsd:element name="codigo" type="xsd:long" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="nombre" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="descripcion" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioTRESb.xml
<?xml version="1.0" encoding="UTF-8" ?>
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicioTRESb.xsd">
        <raton>
            <codigo>120</codigo>
            <nombre>razer</nombre>
            <descripcion>raton inalambrico</descripcion>
        </raton>



        <teclado>
            <codigo>128</codigo>
            <nombre>razer</nombre>
            <descripcion>teclado mecanico</descripcion>
        </teclado>



        <monitor>
            <codigo>230</codigo>
            <nombre>Samsung 2000</nombre>
            <descripcion>Tele de gama alta</descripcion>
        </monitor>
</productos>
