=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioTRES.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:complexType name="atributos">
        <xsd:sequence>
            <xsd:element name="codigo" type="xsd:long" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="nombre" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="descripcion" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoproductos">
        <xsd:sequence>
            <xsd:element name="raton" minOccurs="0" maxOccurs="1" type="atributos"/>
            <xsd:element name="teclado" minOccurs="0" maxOccurs="1" type="atributos"/>
            <xsd:element name="monitor" minOccurs="0" maxOccurs="1" type="atributos"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="cantproductos">
        <xsd:sequence>
            <xsd:element name="producto" minOccurs="1" maxOccurs="unbounded" type="tipoproductos"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="productos" type="cantproductos">

    </xsd:element>
</xsd:schema>

=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioTRES.xml
<?xml version="1.0" encoding="UTF-8" ?>
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicioTRES.xsd">
    <producto>
        <raton>
            <codigo>120</codigo>
            <nombre>razer</nombre>
            <descripcion>raton inalambrico</descripcion>
        </raton>
    </producto>

    <producto>
        <teclado>
            <codigo>128</codigo>
            <nombre>razer</nombre>
            <descripcion>teclado mecanico</descripcion>
        </teclado>
    </producto>

    <producto>
        <monitor>
            <codigo>230</codigo>
            <nombre>Samsung 2000</nombre>
            <descripcion>Tele de gama alta</descripcion>
        </monitor>
    </producto>

</productos>
