=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioCUATRO.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:complexType name="infoVenta">
    <xsd:sequence>
        <xsd:element name="Importe" type="xsd:float" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="Comprador" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="Fecha" type="xsd:date" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="Vendedor" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="codigo" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
</xsd:complexType>


<xsd:complexType name="tipoListaVentas">
<xsd:sequence>
    <xsd:element name="venta" minOccurs="1" maxOccurs="unbounded" type="infoVenta"/>
</xsd:sequence>
</xsd:complexType>

<xsd:element name="listaVentas" type="tipoListaVentas">

</xsd:element>
</xsd:schema>

=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioCUATRO.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listaVentas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicioCUATRO.xsd">
<venta>
    <Importe>23.34</Importe>
    <Comprador>Anxo</Comprador>
    <Vendedor>SinPa</Vendedor>
    <codigo>U8ISU</codigo>
</venta>

    <venta>
        <Importe>34.12</Importe>
        <Comprador>Alejandro</Comprador>
        <Vendedor>Gaalpos</Vendedor>
        <codigo>803JGUI3</codigo>
    </venta>

    <venta>
        <Importe>50.05</Importe>
        <Comprador>Pepe</Comprador>
        <Vendedor>Angel</Vendedor>
        <codigo>8ONHF843</codigo>
    </venta>

</listaVentas>
