=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioOCHO.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!--Elemento raiz listacursos-->
    <xsd:element name="listacursos" type="tLista"/>
    
    <xsd:complexType name="tLista">
        <xsd:sequence>
            <xsd:element name="cursos" type="tCurso" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tCurso">
        <xsd:sequence>
            <xsd:element name="alumno" type="tAlumno" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <!--Declaracion de grupo de algo-->
    <xsd:complexType name="tAlumno">
        <xsd:sequence>
            <xsd:group ref="tDatos"/>
            <xsd:element name="listaAsignaturas" type="tListaAsignaturas"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tListaAsignaturas">
        <xsd:sequence>
            <xsd:element name="asignatura" type="tAsignatura" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tAsignatura">
        <xsd:sequence>
            <xsd:element name="nombre" type="xsd:string"/>
            <xsd:element name="profesor" type="tProfesor"/>
        </xsd:sequence>
        <xsd:attribute name="codigo" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="tProfesor">
        <xsd:sequence>
            <xsd:element name="nrp" type="xsd:string"/>
           <xsd:group ref="datosBasicos"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:group name="tDatos">
        <xsd:sequence>
            <xsd:element name="dni" type="xsd:string"/>
            <xsd:group ref="datosBasicos"/>
        </xsd:sequence>
    </xsd:group>

    <!-- Datos basicos para alumno y profesor-->
    <xsd:group name="datosBasicos">
        <xsd:sequence>
            <xsd:element name="nombre" type="xsd:string"/>
            <xsd:element name="apellidoUno" type="xsd:string"/>
            <xsd:element name="apellidoDos" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
    </xsd:group>

    <!--Como evitar la duplicidad de declaracion de NOMBRE apellido1 y apellido2-->

</xsd:schema>

=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioOCHO.xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listacursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicioOCHO.xsd">
  <!--1 or more repetitions:-->
  <cursos>
    <!--1 or more repetitions:-->
    <alumno>
      <dni>string</dni>
      <nombre>string</nombre>
      <apellidoUno>string</apellidoUno>
      <!--Optional:-->
      <apellidoDos>string</apellidoDos>
      <listaAsignaturas>
        <!--1 or more repetitions:-->
        <asignatura codigo="string">
          <nombre>string</nombre>
          <profesor>
            <nrp>string</nrp>
            <nombre>string</nombre>
            <apellidoUno>string</apellidoUno>
            <!--Optional:-->
            <apellidoDos>string</apellidoDos>
          </profesor>
        </asignatura>
      </listaAsignaturas>
    </alumno>
  </cursos>
</listacursos>
