=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioCINCO.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:complexType name="atributosTres">
        <xsd:sequence>
            <xsd:element name="cantidad" minOccurs="1" maxOccurs="1" />
            <xsd:element name="divisa" minOccurs="1" maxOccurs="1" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="atributosDos">
        <xsd:sequence>
            <xsd:element name="fechafinpago" minOccurs="0" />
            <xsd:element name="cantidad" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="atributos">
        <xsd:sequence>
            <xsd:choice>
            <xsd:element name="ventaCredito"  type="atributosDos"/>
            <xsd:element name="ventaInmediata" type="atributosTres"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="tipoVenta">
        <xsd:sequence>
            <xsd:element name="venta" minOccurs="1" type="atributos"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="tipolistaVentas">
        <xsd:sequence>
            <xsd:element name="listaCompras" minOccurs="1" maxOccurs="unbounded" type="tipoVenta"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="listaVentas" type="tipolistaVentas">

    </xsd:element>
</xsd:schema>

=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioCINCO.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listaVentas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="ejercicioCINCO.xsd">

    <listaCompras>
        <venta>
            <ventaCredito>
                <fechafinpago></fechafinpago>
                <cantidad></cantidad>
            </ventaCredito>
        </venta>

        <venta>
            <ventaInmediata>
                <cantidad></cantidad>
                <divisa></divisa>
            </ventaInmediata>
        </venta>
    </listaCompras>

    <listaCompras>

        <venta>
            <ventaCredito>
                <cantidad></cantidad>
            </ventaCredito>
        </venta>


    </listaCompras>

</listaVentas>
