=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioDOS.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="listaPedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedidos" minOccurs="1" maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="serie"/>
                            <xs:element name="cantidad"/>
                            <xs:element name="peso"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Anxo55/marcasAnxo/2ªEV/XML/apuntes/ejercicioDOS.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listaPedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema"
xsi:noNamespaceSchemaLocation="ejercicioDOS.xsd">
    <pedidos>
        <serie></serie>
        <cantidad></cantidad>
        <peso></peso>
    </pedidos>

    <pedidos>
        <serie></serie>
        <cantidad></cantidad>
        <peso></peso>
    </pedidos>

    <pedidos>
        <serie></serie>
        <cantidad></cantidad>
        <peso></peso>
    </pedidos>

</listaPedidos>
